name: darna
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  animations: ^2.1.1
  cached_network_image: ^3.4.1
  cloud_firestore: 6.1.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  envied: ^1.3.3
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  json_annotation: ^4.10.0
  lucide_icons_flutter: ^3.1.9
  shared_preferences: ^2.5.4

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  json_serializable: ^6.12.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/constants/
  filename: app_image.dart
  field_prefix: null
  ignore_comments: true
  classname: AppImage
